---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: debian-8.6
  - name: fedora-24
  - name: fedora-25
  - name: opensuse-13.2
  - name: opensuse-leap-42.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

busser:
  sudo: true

suites:
  - name: default
    run_list:
      - recipe[asf::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      asf:
        bots:
          bot_name:
            AcceptConfirmationsPeriod: 0
            AcceptGifts: false
            CardDropsRestricted: true
            CustomGamePlayedWhileFarming: null
            CustomGamePlayedWhileIdle: null
            DismissInventoryNotifications: true
            DistributeKeys: false
            Enabled: false
            FarmingOrder: 0
            FarmOffline: false
            ForwardKeysToOtherBots: false
            GamesPlayedWhileIdle: []
            HandleOfflineMessages: false
            IsBotAccount: false
            LootableTypes: [1, 3, 5]
            PasswordFormat: 0
            Paused: false
            RedeemingPreferences: 0
            SendOnFarmingFinished: false
            SendTradePeriod: 0
            ShutdownOnFarmingFinished: false
            SteamApiKey: null
            SteamLogin: null
            SteamMasterClanID: 0
            SteamMasterID: 0
            SteamParentalPIN: 0
            SteamPassword: null
            SteamTradeToken: null
            TradingPreferences: 1
